DjangoProjects/channelx/channelx/urls.py
from django.contrib.auth import views as auth_views
from users import views as user_views
from django.urls import path, include
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from main import urls as main_urls
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('main.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('profile/', user_views.profile, name='profile'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='users/pword_reset.html'), name='pword_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/pword_reset_done.html'), name='pword_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/pword_reset_confirm.html'), name='pword_reset_confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/pword_reset_complete.html'), name='pword_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoProjects/channelx/main/urls.py
from django.urls import path
from django.conf.urls import include
from django.urls import path, re_path
from . import views
from users import views as users_views
from . import views
from .views import (
    MemberListView,
    ChannelListView,
    ChannelDetailView,
    ChannelCreateView,
    ChannelUpdateView, 
    ChannelDeleteView,
    TicketCreateView
)

urlpatterns = [
    path('', views.homepage, name='main-home'),
    path('', ChannelListView.as_view()),
    path('about/', views.aboutpage, name='main-about'),
    path('findchannel/', views.join_channel, name='main-findchannel'),
    path('register/', users_views.register, name='users-register'),
    path('profile/', users_views.profile, name='profile'),
    path('channelsettings/', views.channelsettingspage, name='main-channelsettings'),
    path('thankyouregister/', views.thankyouregisterpage, name='main-thankyouregister'),
    path('ticketrecieved/', views.ticketrecivedpage, name='main-ticketrecieved'),
    path('channel/', ChannelListView.as_view(), name='main-channel-list'),
    path('channel/new/', ChannelCreateView.as_view(), name='channel-create'),
    path('channel/<str:slug>/', ChannelDetailView.as_view(), name='channel-detail'),
    path('channel/<str:slug>/update/', ChannelUpdateView.as_view(), name='channel-update'),
    path('channel/<str:slug>/delete/', ChannelDeleteView.as_view(), name='channel-delete'),
    path('ticketrequest/', TicketCreateView.as_view(template_name='main/ticketRequest.html'), name='main-ticketrequest'),

]

DjangoProjects/channelx/main/models.py
from django.db import models
from django.utils import timezone
from datetime import date, datetime
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.template.defaultfilters import slugify

class Channel(models.Model):
    room_name = models.CharField(max_length=30, unique=True)
    start_life = models.DateField(default=date.today, null=True)
    expire_date = models.DateField(default=date.today, null=True)
    start_quiet_hour = models.TimeField(default=datetime.now, blank=True)
    end_quiet_hour = models.TimeField(default=datetime.now, blank=True)
    room_owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    slug = models.SlugField(max_length=30, blank=True)

    def save(self, *args, **kwargs):
        self.slug = self.slug or slugify(self.room_name)
        super(Channel, self).save(*args, **kwargs)

    def __str__(self):
        return self.room_name

    def get_absolute_url(self):
        return reverse("channel-detail", kwargs={"slug": self.slug})

    @property
    def quiet_hours(self):
        now = datetime.now().time()
        return self.start_quiet_hour <= now < self.end_quiet_hour

class ChannelMembers(models.Model):
    channel_id = models.IntegerField(unique=False, null=True, blank=False)
    member_id = models.IntegerField(unique=False, null=True, blank=False)
    


class Ticket(models.Model):
    issue = models.CharField(max_length=50)
    problem_details = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        super(Ticket, self).save(*args, **kwargs)

    def __str__(self):
        return self.problem_details

    def get_absolute_url(self):
        return reverse('ticketRecieved', kwargs={'pk': self.pk})
        
class Messages(models.Model):
    room = models.ForeignKey(Channel, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    date = models.DateTimeField(auto_now=True, db_index=True)
    text = models.TextField()

    def to_data(self):
        out = {}
        out['id'] = self.room
        out['from'] = self.user
        out['text'] = self.text
        return out

DjangoProjects/channelx/main/forms.py
from django import forms


class Channel(forms.ModelForm):
    class Meta:
        fields = ['room_name',
                  'start_life',
                  'expire_date',
                  'start_quiet_hour',
                  'end_quiet_hour',
                  'room_owner']

class JoinChannelForm(forms.Form):
    requestedChannel = forms.CharField(label="Channel Name", max_length=30)
    fields = ['room_name', 'start_life', 'expire_date', 'start_quiet_hour',
            'end_quiet_hour', 'room_owner']

class Ticket(forms.Form):
    issue = forms.CharField(max_length=50)
    problem_details = forms.CharField(widget=forms.Textarea)

DjangoProjects/channelx/main/views.py
from datetime import date, datetime
import json
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from main.models import Channel, ChannelMembers, Ticket, Messages
from django.core.mail import send_mail
from django.utils.safestring import mark_safe
from main.forms import JoinChannelForm
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, HttpResponseNotAllowed
import json


def homepage(request):
    return render(request, "main/home.html", {"title": "Home"})

@login_required
def join_channel(request):
    if request.method == 'POST':
        form = JoinChannelForm(request.POST)
        if form.is_valid():
            try:
                cname = form.cleaned_data.get("requestedChannel")
                cid = Channel.objects.get(room_name=cname).id
                new_member = ChannelMembers()
                new_member.channel_id = cid
                new_member.member_id = request.user.id
                new_member.save()
                messages.success(request, f'You have joined {cname}')
                return redirect("main-findchannel")
            except ChannelMembers.DoesNotExist:
                messages.success(request, f'Channel does not exist')
                return redirect("main-findchannel")
    else:
        form = JoinChannelForm()
    return render(request, 'main/findChannel.html', {'form': form})

class BaseLayout(ListView):
    model = Channel
    context_object_name = "channels"
    template_name = "main/base.html"
    
# class ChannelListView(ListView):
#     def post(request, slug):
#         if request.method == 'POST':
#             room = Channel.objects.get(room_name = slug)
#             mfrom = request.POST['from']
#             text = request.POST['text']

#             msg = Message(room=room, user = mfrom, text=text)
#             msg.save()
#             body = json.dumps(msg.to_data())

#             return HttpResponse(body, content_type = 'application/json')
#         else:
#             room_owner = request.GET.get('user')
#             room = Channel.objects.get(slug=slug, room_owner=request.user)
#             cmsgs = Messages.objects.filter(
#                 room=room).order_by('-date')[:50]
#             msgs=[]
#             for msg in reversed(cmsgs):
#                 msgs.append(msg.to_data())
        
#         return render(request, 'main/channel_detail.html', {'slug' : slug})
    


class ChannelListView(LoginRequiredMixin, ListView):
     model = Channel
     context_object_name = "channels"

class MemberListView(LoginRequiredMixin, ListView):
    model = ChannelMembers
    template_name = "main/channel_detail.html"

class ChannelDetailView(LoginRequiredMixin, DetailView):
    model = Channel
    template_name = "main/channel_detail.html"
    def post(request, slug):
        if request.method == 'POST':
            room = Channel.objects.get(room_name = slug)
            mfrom = request.POST['from']
            text = request.POST['text']

            msg = Message(room=room, user = mfrom, text=text)
            msg.save()
            body = json.dumps(msg.to_data())

            return HttpResponse(body, content_type = 'application/json')
        else:
            room_owner = request.GET.get('user')
            room = Channel.objects.get(slug=slug, room_owner=request.user)
            cmsgs = Messages.objects.filter(
                room=room).order_by('-date')[:50]
            msgs=[]
            for msg in reversed(cmsgs):
                msgs.append(msg.to_data())
        
        return render(request, 'main/channel_detail.html', {'slug' : slug})

class ChannelCreateView(LoginRequiredMixin, CreateView):
    model = Channel
    fields = ["room_name", "expire_date", "start_quiet_hour", "end_quiet_hour", "slug"]

    def form_valid(self, form):
        form.instance.room_owner = self.request.user
        form.instance.start_life = date.today()
        return super().form_valid(form)


class ChannelUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Channel
    template_name = 'main/channelSettings.html'
    fields = ["room_name", "expire_date", "start_quiet_hour", "end_quiet_hour", "slug"]

    def form_valid(self, form):
        form.instance.room_owner = self.request.user
        form.instance.start_life = date.today()
        return super().form_valid(form)

    def test_func(self):
        channel = self.get_object()
        if self.request.user == channel.room_owner:
            return True
        return False

class ChannelDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Channel
    success_url = "/channel/"

    def test_func(self):
        channel = self.get_object()
        if self.request.user == channel.room_owner:
            return True
        return False

class TicketCreateView(CreateView):
    model = Ticket
    template_name = 'main/tickeRequest.html'
    fields = ['issue', 'problem_details']
    now = datetime.now()

    def form_valid(self, form):
        form.instance.author = self.request.user
        send_mail(f'Ticket created by {form.instance.author} {self.now}', f'{self.fields}', 'WTAMU ChannelX Tickets', [f'wtchanx2019@gmail.com',])
        return redirect('main-ticketrecieved')

def aboutpage(request):
    return render(request, "main/about.html", {"title": "About"})

@login_required
def channelinfopage(request, room_name):
    return render(request, 'main/channel_detail.html', {'room_name_json': mark_safe(json.dumps(room_name))})

@login_required
def channelsettingspage(request):
    return render(request, "main/channelSettings.html", {"title": "Channel Settings"})

def thankyouregisterpage(request):
    return render(request, "main/thankYouReqister.html", {"title": "Thank You"})

def ticketrecivedpage(request):
    return render(request, "main/ticketRecieved.html", {"title": "Ticket Sent"})

def ticketrequestpage(request):
    return render(request, 'main/ticketRequest.html', {"title": "Report an Issue"})
    

DjangoProjects/channelx/main/templates/main/about.html
{% extends "main/base.html" %}
{% block content %}
<head>
  <title>about</title>
  <style>
    p {color:white; text-align:left; font-size:20px}
</style>
</head>

<body>

  <div class="col-12" style="text-align:center; border-radius: 10px; border: 1px solid black; background-color:#293132">
    <h1 style="text-align:center;font-size:60px;color:#00BFFF">ChannelX</h1>
    <h3><a href="http://score-contest.org/2018/projects/channelx.php">
      SCORE Project: <i>ChannelX</i> </a></h3>
    <h5 style="color:white">Transient Shared Communication Channels</h5>
    <p><b>Sponsor</b>: Christine Julien</p>
    <p>With the availability of e-mail, SMS, Slack, and many other messaging
       applications, many channels exist for connecting two or more people.
       However, existing channels permanently associate an identifier with a
       user, making the user always reachable at the same handle. However, many
       of our activities require communication channels that are more transient
       in nature. Many times, we do not really want to give an otherwise
       perfect stranger our phone number, but we do want that person to be able
       to contact us, potentially for a limited time or in limited
       circumstances. For instance, a university teaching assistant may want to
       make a channel available to students in a course only during designated
       "available" hours and only for the duration of a semester. A seller (or
       buyer) on a service like Craigslist may want to create a channel of
       availability for the duration of a given transaction. By making these
       transient channels available, a user can protect his or her identity and
       the more direct channels (e.g., not having to give a phone number out to
       a potential buyer on Craigslist). The goal of this project is to create
       a service that supports the creation of such transient channels with
       user-friendly names, associates them with (hidden) permanent handles for
       the users, and manages the lifecycle of the created channels.</p>

  <p><b>Project Description</b></p>
   <p>ChannelX will make it possible to create, share, and destroy transient
     communication channels. These channels should be tied to users' existing
     communication streams (e.g., SMS, e-mail, etc.) without exposing the
     user's actual phone number or e-mail address. To fully manage the
     lifecycle of transient channels, the application should allow a user to:<br>
     manage a profile, in which the application stores the concrete direct
     contact channels for the user (e.g., phone number, e-mail) and preferences
     (e.g., default available times, default contact means, etc.);<br>
     create a new obfuscated communication channel and associate with it
     properties of its availability (e.g., available schedule, times, length
     of life, restrictions to specific users or types of users (optional), etc.)
      and associated direct contact mean(s);<br>
    choose or be given an-easy-to-share "name" of the channel (e.g., "blue
    balloon"); channel names should follow some easy pattern and should be easy
    to share both orally and written;<br>
    join a channel given its obfuscated name; and delete a channel.<br>
    Within a channel, the users can be required to be identified by their
    actual names, or, optionally, channels should be able to be defined to
    allow participants to assume personae using names selected from some
    predefined set (e.g., animal names, food names, etc.).<br>
    Profiles and channel mappings should be stored in a backend to
    facilitate joining and deleting channels.</p>

   <p><b>Project Scope</b></p>
   <p>The project should support the features described above. In addition,
     optional features could be added to the application at the team's
     discretion, but these features should not supplant the required features
     nor should they interfere with the required features. The project can
     support other actual communication types other than SMS and e-mail using
     the APIs available for those services, but it should at a minimum support
     phone numbers and e-mail addresses. The application must support
     text-based communication but could also opt to support audio and/or video,
     either synchronously or asynchronously.

     The project should provide a web-based interface but the team may also opt
     to provide a mobile application for one or more mobile OSs as desired.

     The project must include high quality documentation, including documents
     on the process (see below) and a (brief) user manual that describes how
     to get started with the application.</p>

   <p><b>Process Requirements</b></p>
   <p>Teams can adopt any development process. Project artifacts must be stored
     in a public repository with issue tracking facilities (e.g., GitHub). The
     team should also perform some formal project tracking, including defining
     milestones in advance, assigning roles to team members, developing a
     testing plan, etc. The team should pay particular attention to the
     usability of the application.

   <p><b>Environmental Constraints</b></p>
   <p>The application should be web-based and must run on most modern browsers
     (e.g., Chrome, Firefox, Internet Explorer). Backend platforms to be used
     are up to the team to determine. Design that is compatible with use on a
     smartphone is encouraged; teams may even opt to make native one or more
     native applications for various mobile OSs.</p>

   <p><b>Level of Sponsor Involvement</b></p>
   <p>The sponsor of this project will accept questions via email about the
     project topic at any time. Brief Skype meetings can be arranged on demand
     if necessary.</p>
   <p><b>Sponsor contact: c (dot) julien (at) utexas (dot) edu</b></p>

   <p><b>Project Restrictions</b></p>
   <p>None.</p>




</body>

{% endblock content %}

DjangoProjects/channelx/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang='en-US'>
<!-- 
    Last Update: 
        05/06/19 by Tarren Bos 

    This is a base template for the entire site. All templates are routed through this code in
    order to use the NavBar and all installed addons
-->

<!-- Header and Title -->
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'main/main.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- jQuery CDN -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    {% if title %}
        <title>ChannelX - {{ title }}</title>
    {% else %}
        <title>ChannelX</title>
    {% endif %}
</head>

<!--- Items on page -->
<body>
   <header class="site-header">
        <!-- The Navigation Bar -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-steel fixed-top">
            <div class="container"> <!-- Causes page to be a specific length of 12 cols -->
                <a class="navbar-brand" href="{% url 'main-home' %}">ChannelX</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigaiton">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- The Left Side of the NavBar -->
                    <div class="navbar-nav mr-auto">
                        <a class="nav-link" href="{% url 'main-about' %}">About</a>
                        {% if user.is_authenticated %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Channel</a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{% url 'main-findchannel' %}">Find Channel</a>
                                    <a class="dropdown-item" href="{% url 'channel-create' %}">Create Channel</a>
                                    <a class="dropdown-item" href="{% url 'main-channel-list' %}">Channel List</a>
                                </div>
                            </li> 
                        {% endif %}
                    </div>
                    <!-- The Right Side of the NavBar -->
                    <div class="navbar-nav">
                        <a class="nav-link" href="{% url 'main-ticketrequest' %}">Ticket</a>
                        {% if user.is_authenticated %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">My Account</a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{% url 'profile' %}">Profile</a>
                                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                                </div>
                            </li> 
                        {% else %}
                            <a class="nav-link" href="{% url 'login' %}">Login</a>
                            <a class="nav-link" href="{% url 'users-register' %}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="container">
        <div class="row">
            <!-- The Channel List SideBar -->

            <div class="col">
                <!-- Messages from site displayed below the NavBar -->
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                <!-- Template pages are routed through the blocked content to use this base template -->
                {% block content %}{% endblock %}
            </div>
        </div>
    </main>
</body>
</html>

DjangoProjects/channelx/main/templates/main/channelSettings.html
{% extends "main/base.html" %}
{% block content %}
{% load crispy_forms_tags %}

<!--Channel information & Schedule-->
<div class="container-fluid">
    <div class="row content">
        <div class="col" style="text-align:center; border-radius: 10px; background-color:#293132">
            <!-- Channel List -->
            <h2 style="color:#00BFFF">Edit Channel</h2>
            <!-- Search Channel -->
            <div>
                <form class="form-group" method="post" style="color:white; width:100%; padding: 0 25% 10% 25%">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button style="width:100px; float:left;" type="submit" class="btn btn-secondary">Save</button>
                    <a style="width:100px; float:right;" class="btn btn-danger" href="{% url 'channel-delete' object.slug %}">Delete</a>
                </form>
            </div>
        </div>


        <!--Contact list-->
        <div class="col-4" style="text-align:center; border-radius: 10px; background-color:#293132">
            <h2 style="color:#00BFFF; text-align: center">Channel Users</h2>
            <div class="search-container" style="padding:10px">
                <form action="/action_page.php">
                <input type="text" placeholder="Search.." name="search">
                <button type="submit"><i class="fa fa-search"></i></button>
                </form>
            </div>
            <section style="padding:5%">
                <div class="table-wrapper-scroll-y" style="border-radius: 10px; background-color:white">
                <table style="width:100%; text-align:left">
                    <tbody>
                    <tr> <td>User Alias 1</td> </tr>
                    <tr> <td>User Alias 2</td> </tr>
                    <tr> <td>User Alias 3</td> </tr>
                    <tr> <td>User Alias 4</td> </tr>
                    <tr> <td>User Alias 5</td> </tr>
                    <tr> <td>User Alias 6</td> </tr>
                    <tr> <td>User Alias 7</td> </tr>
                    <tr> <td>User Alias 8</td> </tr>
                    <tr> <td>User Alias 9</td> </tr>
                    </tbody>
                </table>
                </div>
            </section>
            <p>
                <button class="button">Remove User<br>(NotActive)</button>
            </p>
        </div>
    </div>
</div>
{% endblock content %}

DjangoProjects/channelx/main/templates/main/channel_detail.html
{% extends "main/base.html" %}
{% block content %}
{% load static %}

<div class="container-fluid">
    <div class="row content">
        <!-- Channel Information -->
        <div class="col-4" style="border-radius: 10px; background-color:#293132">
            <p style="color:white">Channel Name: {{ object.room_name }}</p>
            <p style="color:white">Channel Owner: {{ object.room_owner }}</p>
            <p style="color:white">Channel Type: -----</p>
            <p style="color:white">Your Alias: {{ user.profile.anon }} </p>
            <p style="color:white">Schedule: </p>
            <div style="border-radius: 10px; background-color:white">
                <p style="padding: 0 0 0 5px">Channel Life:</p>
                <p style="padding: 0 0 0 5px">{{ object.start_life }} - {{ object.expire_date }}</p>
                <br>
                <p style="padding: 0 0 0 5px">Quiet Hours:</p>
                <p style="padding: 0 0 0 5px">{{ object.start_quiet_hour }} - {{ object.end_quiet_hour }}</p>
            </div><br>
            {% if user == object.room_owner %}
                <p><a href="{% url 'channel-update' channel.slug %}"><button class="btn btn-secondary btn-block">Edit Channel Settings</button></a></p>
            {% endif %}
            <br>
        </div>

        <!-- MESSAGING SYSTEM -->
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

        <div class="col-5" style="text-align:center; border-radius: 10px; background-color:#293132">
            <h2 style="color:#00BFFF">Messages</h2>
            <!-- PLACE CHAT IN BETWEEN HERE-->
            <div style="border: 1px solid black; background-color:white">
                <textarea id="chat-log" cols="50" rows="10"></textarea>
                <script>
                    var chatlist = document.getElementById('chat-log');
                    chatlist.scrollTop = chatlist.scrollHeight;
                </script>
            </div>
            <section style="width:100%; margin-top:15px">
                <input id="chat-input" type="text" size="50"/><br/>
            </section>
            <p>
                <br><input id="chat-submit" type="button" value="Send"/>
            </p>
            <script>
                $(document).ready(function () {
                    $('#chat-submit').click(function () {
                        var user = "{{ user.profile.anon }}";
                        var text = user + ": " + $('#chat-input').val() + "\n";
                        $('#chat-log').html($('#chat-log').html() + text);
                        $('#chat-input').val('');
                    });
                    $.post('channel/{{ slug }}', { from: user, text: text });
                });
            </script>
        </div>

        <!--Contact list-->
        <div class="col-3" style="padding:5px; border-radius: 10px; text-align:center; background-color:#293132">
            <h2>Contact List</h2>
            <div class="table-wrapper-scroll-y" style="border: 1px solid black; background-color:white">
                {% for channelmembers in channelmembers_list %}
                    <p style='margin:auto; padding:0px 0px 10px 0px'>
                        <a href="#"><button style="padding-bottom: 5px" class='btn btn-secondary btn-block'>{{ channelmembers.member_id }}</button></a>
                    </p>
                    {% if channelmembers.channel_id == object.pk %}
                        <p style='margin:auto; padding:0px 0px 10px 0px'>
                            <a href="#"><button style="padding-bottom: 5px" class='btn btn-secondary btn-block'>{{ channelmembers.member_id }}</button></a>
                        </p>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% if object.quiet_hours %}
    <script>
        alert("This channel is in quiet hours!");
    </script>
{% endif %}

{% endblock content %}

DjangoProjects/channelx/main/templates/main/channel_form.html
{% extends "main/base.html" %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<div class="container-fluid">
    <div class="row content">
        <div class="col-12" style="text-align:center; border-radius: 10px; border: 1px solid black; background-color:#293132">
            <h2 style="color:#00BFFF">Create a Channel</h2>
            <form class="form-group" method="post" style="color:white; width:100%; padding: 0 25% 0 25%;">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-secondary">Create</button>
            </form>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $("#id_slug").prop('disabled', true);
        $("#div_id_slug").hide();
        $("#id_room_name").on("change keyup", function() {
            var slug_name = $("#id_room_name").val();
            slug_name = slug_name.replace(/ /g, "-");
            $("#id_slug").val(slug_name);
            console.log($("#id_slug").val());
        })
    });
</script>

{% endblock %}